In [1]:
# tf : 單字 在每一篇文章出現次數(每篇文章都出現airplane) 越多字 評分越高 
# idf : inverse-df : 每一單字跨文章出現次數(越多越沒有代表性 airplane) 同一單字 跨越多篇文章 評分越低 
# tf * idf = 數字越大越好
#  (單字出現頻率 / 該篇有多少單字) * log( 所有文章的篇數 / 有出現幾篇)

In [1]:
import numpy as np
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfTransformer
from sklearn.metrics.pairwise import cosine_similarity
base = 1 # 從四篇文章中取出指定的那一篇[0, 1, 2, 3]
#Case subject
subject = [
    '[OSCE XG 1876] windows 10 update 1809 asking us to uninstall trend micro',
    'Clients Not showing online on Console',
    '[OSCE XG] Windows feature pack 1809', 
    'I have one cute cat',
]
vectorizer = CountVectorizer() # 準備將文字轉換後，計算出現頻率
X = vectorizer.fit_transform(subject)
#word = vectorizer.get_feature_names()
#print(word)
print(X.toarray()) # 該部分就是 文字轉代碼，類似 影像轉代碼

transformer = TfidfTransformer() # 針對每一個單字加上 weight
tfidf = transformer.fit_transform(X)
#np.set_printoptions(precision=5)
print(tfidf.toarray())

# 想知道每一篇文章 跟其他篇文章相似程度 以下是使用統計的方式 
# 從已經加上weight的數據，去使用cosine similarity 去比較文章的相似度
#cosine_similarity(tfidf[base], tfidf).ravel()
similarity_subject = np.array(cosine_similarity(tfidf[base], tfidf)).ravel()
print(similarity_subject)

[[1 1 1 1 0 0 0 0 0 0 1 0 0 0 0 1 0 0 1 1 1 1 1 1 1]
 [0 0 0 0 0 1 1 0 0 0 0 1 1 0 1 0 0 1 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0 1 0 0 0 0 0 0 1 1 0 0 0 0 0 0 1 1]
 [0 0 0 0 1 0 0 1 0 1 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0]]
[[0.29505881 0.23262775 0.29505881 0.29505881 0.         0.
  0.         0.         0.         0.         0.29505881 0.
  0.         0.         0.         0.23262775 0.         0.
  0.29505881 0.29505881 0.29505881 0.29505881 0.29505881 0.23262775
  0.23262775]
 [0.         0.         0.         0.         0.         0.40824829
  0.40824829 0.         0.         0.         0.         0.40824829
  0.40824829 0.         0.40824829 0.         0.         0.40824829
  0.         0.         0.         0.         0.         0.
  0.        ]
 [0.         0.37222485 0.         0.         0.         0.
  0.         0.         0.47212003 0.         0.         0.
  0.         0.         0.         0.37222485 0.47212003 0.
  0.         0.         0.         0.         0.         0.37222485

In [2]:
import numpy as np
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfTransformer
from sklearn.metrics.pairwise import cosine_similarity
base = 1 # 從四篇文章中取出指定的那一篇[0, 1, 2, 3]
#Case subject
subject = [
    '[OSCE XG 1876] windows 10 update 1809 asking us to uninstall trend micro',
    'Clients Not showing online on Console',
    '[OSCE XG] Windows feature pack 1809', 
    'I have one cute cat',
]

In [4]:
vectorizer = CountVectorizer() # 準備將文字轉換後，計算出現頻率
X = vectorizer.fit_transform(subject)
#word = vectorizer.get_feature_names()
#print(word)
print(X.toarray()) # 該部分就是 文字轉代碼，類似 影像轉代碼

transformer = TfidfTransformer() # 針對每一個單字加上 weight
tfidf = transformer.fit_transform(X)
#np.set_printoptions(precision=5)
tfidf.toarray()

[[1 1 1 1 0 0 0 0 0 0 1 0 0 0 0 1 0 0 1 1 1 1 1 1 1]
 [0 0 0 0 0 1 1 0 0 0 0 1 1 0 1 0 0 1 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0 1 0 0 0 0 0 0 1 1 0 0 0 0 0 0 1 1]
 [0 0 0 0 1 0 0 1 0 1 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0]]


array([[0.29505881, 0.23262775, 0.29505881, 0.29505881, 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.29505881, 0.        , 0.        , 0.        , 0.        ,
        0.23262775, 0.        , 0.        , 0.29505881, 0.29505881,
        0.29505881, 0.29505881, 0.29505881, 0.23262775, 0.23262775],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.40824829, 0.40824829, 0.        , 0.        , 0.        ,
        0.        , 0.40824829, 0.40824829, 0.        , 0.40824829,
        0.        , 0.        , 0.40824829, 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.37222485, 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.47212003, 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.37222485, 0.47212003, 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.

In [3]:
#Case body
body = [    
    'Altaan called in regarding recent windows 10 update 1809 asking us to uninstall trend micro . Unloading agents will allow the installation of 1809 upgrade',
    'Clients Not showing online on Console \\Suddenly clients on the server went 0',
    'Windows feature pack 1809 reports an incompatibility with Trend. Forces an uninstall in order to update Windows. I then manually reinstall Trend without any issues but when manually scanning files Office scan hangs and i have to run an end task.',
    'How is weather today in Taipei',
]

vectorizer = CountVectorizer()
X = vectorizer.fit_transform(body)
word = vectorizer.get_feature_names()
#print(word)
transformer = TfidfTransformer()
tfidf = transformer.fit_transform(X)
body_subject = np.array(cosine_similarity(tfidf[base], tfidf)).ravel()
print(body_subject)

[1.         0.03382064 0.20835866 0.03767698]


In [4]:
values = similarity_subject * 0.5 + body_subject * 0.5
values

array([1.        , 0.01691032, 0.277359  , 0.01883849])

In [5]:
# 50 : 50 weight
values = similarity_subject * 0.5 + body_subject * 0.5
# remove myself

values[base] = 0 
# find best solution
index = np.argmax(values)
# print out sugesiton only similarity > 0.1
if values[index] > 0.1:
    print('Similarity {}'.format(values[index]))
    print('---------------------------------------------------------------')
    print('Src Subject : ','\n', subject[base])
    print('Src Body :','\n', body[base])
    print('---------------------------------------------------------------')
    print('Prd Subject : ','\n', subject[index])
    print('Prd Body :','\n', body[index])
else:
    print('Similarity {}'.format(values[index]))
    print('NO_DATA_FOUND')

Similarity 0.27735899520865304
---------------------------------------------------------------
Src Subject :  
 [OSCE XG 1876] windows 10 update 1809 asking us to uninstall trend micro
Src Body : 
 Altaan called in regarding recent windows 10 update 1809 asking us to uninstall trend micro . Unloading agents will allow the installation of 1809 upgrade
---------------------------------------------------------------
Prd Subject :  
 [OSCE XG] Windows feature pack 1809
Prd Body : 
 Windows feature pack 1809 reports an incompatibility with Trend. Forces an uninstall in order to update Windows. I then manually reinstall Trend without any issues but when manually scanning files Office scan hangs and i have to run an end task.
